### ISSUE TITLE
Selected icon showing overlay

### ISSUE THREAD

**Issue by akanksha-paul** [Kwasow/BottomNavigationCircles-Android#12]
![Screenshot_20230803_134053](https://github.com/Kwasow/BottomNavigationCircles-Android/assets/135325641/88db63b1-1a67-4e89-920d-9130844353f9)

Why is my selected icon showing overlay?

       <com.github.kwasow.bottomnavigationcircles.BottomNavigationCircles

        android:id="@+id/bottomNavigation"

        android:layout_width="match_parent"

        android:layout_height="?attr/actionBarSize"

        android:layout_gravity="start|bottom"

        app:circleColor="@color/colorPrimary"

        app:menu="@menu/menu_bottom_navigation_bar"/>

**Comment by Kwasow** [comment]
Hi, to me, it looks like you're using material design 3.0, which is not officially supported by this package. If you want to use this package, you'll have to use material 2.0

 I didn't build support for material design 3.0 because I don't think it suits the new design language.

**Comment by Faiyyaz** [comment]
I know i am too late but just create a theme like this
 
 ```
<style name="BottomNavigationView" parent="Theme.MaterialComponents.DayNight">
        <item name="colorSecondaryContainer">@android:color/transparent</item>
 </style>
```

and then refer the theme like this

```
    <com.github.kwasow.bottomnavigationcircles.BottomNavigationCircles
        android:id="@+id/nav_view"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="0dp"
        android:layout_marginEnd="0dp"
        app:labelVisibilityMode="labeled"
        android:background="?android:attr/windowBackground"
        app:layout_constraintBaseline_toTopOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintLeft_toLeftOf="parent"
        app:layout_constraintRight_toRightOf="parent"
        android:theme="@style/BottomNavigationView"
        app:menu="@menu/bottom_nav_menu" />
```
