### ISSUE TITLE
Change shape of selected item.

### ISSUE THREAD

**Issue by faizanhaidarkhan** [Kwasow/BottomNavigationCircles-Android#4]
So far it was awesome, but how can I change the circle shape to rectangle or my custom shape, like below?
![image](https://user-images.githubusercontent.com/43300714/121330643-a1cacb00-c92f-11eb-994a-c80362d40280.png)

**Comment by Kwasow** [comment]
Such feature isn't available yet, but I'm willing to add it in the coming days. Thanks for the idea!

**Comment by Kwasow** [comment]
I will soon release the changes in the next beta release

**Comment by RidhamKamani26** [comment]
when i select item that time item is show in half cut
